services:
  now:
    build: .
    environment:
      NOW_DOMAIN: "example.org"
      NOW_DATA: "data.json"
    volumes:
      - ./data.json:/app/data.json:ro
      - ./assets:/app/public:ro
    ports:
      - "8000:80"
