services:
  now:
    build: .
    environment:
      NOW_DOMAIN: "example.org"
      NOW_CONFIG: "config.json"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./public:/app/public:ro
    ports:
      - "8000:80"
